import type { Metadata } from "next";
// import { Space_Grotesk } from "next/font/google";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const rubik = Rubik({ weight: "400", subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Kevin Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rubik.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
